#!/bin/bash
GIT_CHECKOUT=false
GIT_DIFF=false

while getopts "tp" opt; do
  case $opt in
    t) 
      GIT_CHECKOUT=true
      shift $((OPTIND-1))
    ;;
    p) 
      GIT_DIFF=true
      shift $((OPTIND-1))
    ;;
  esac
done

FILE="$1"

sed 's/\(->\)\($[][$a-zA-Z0-9_ "'\'']\+\)\((\)/\1{\2}\3/' < "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"

if [ $GIT_DIFF = true ]; then
	git diff "$FILE"
fi

if [ $GIT_CHECKOUT = true ]; then
	git checkout "$FILE"
fi
